added code to extract ensemble forecasts
uace-azmet/azmet-forecast-qa pull request #25
Opened 2022-12-13 23:04 UTC by dlebauer

This code
- downloads forecasts
- downscales using interpolation
- extracts 30 ensemble members of forecasts for each of the 28 azmet stations
- combines these into a dataframe
- plots temperature, as an example

2022-12-13 23:51 UTC, dlebauer commented
![image](https://user-images.githubusercontent.com/464871/207470284-2549d440-e40e-40b3-82c8-dd8cab67290c.png)

2022-12-15 20:32 UTC, Aariq commented
Thanks David!  I'll review this and then either implement it as part of the `targets` workflow or possibly deploy it on RStudio Connect on its own and have it save the data as a pin that the targets workflow can use.

2022-12-20 17:40 UTC, Aariq commented
gefs4cast is buggy, can't get running for now.  Opened issue: https://github.com/eco4cast/gefs4cast/issues/7

2022-12-21 18:51 UTC, Aariq requested changes
I had a lot of issues with gdal and geos system libraries and eventually gave up getting it to work on my laptop and instead tried out rocker/geospatial.  Everything except the animated plot works with that image, so if we do implement GEFS-based QA we can use that as a base image for deployment.

2022-12-21 18:51 UTC, Aariq commented on notes/gefs_forecasts.qmd
> +ens_stats <- ens_long %>%
What is `ens_long`?  Looks like a `pivot_longer()` step is missing.  I think probably: 
```suggestion
library(tidyr)
ens_long <- 
  ens_forecast %>% 
  select(-geometry) %>% 
  pivot_longer(APCP:VGRD, names_to = "var")
  
ens_stats <- ens_long %>% 
```

2022-12-21 18:51 UTC, Aariq commented on notes/gefs_forecasts.qmd
> +for(stn in unique(ens_stats$meta_station_id)){
```suggestion
for(stn in unique(ens_stats$meta_station_name)){
```

2022-12-21 18:51 UTC, Aariq commented on notes/gefs_forecasts.qmd
> +  mutate(id = paste0(meta_station_name, var))
I needed to add a mutate to parse `time` to get the plots to work.
```suggestion
  mutate(id = paste0(meta_station_name, var), time = lubridate::ymd_hms(time))
```

2022-12-21 18:51 UTC, Aariq commented on notes/gefs_forecasts.qmd
> +           fps=10, save_as = "temp.gif")
Requires packge `gifski` which requires some system library that isn't in rocker/geospatial.  Cool idea, but probably won't implement in the qa/qc report.

2025-02-14 18:26 UTC, closed without merging